name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt -t .
          fi
          
      - name: Create deployment package
        run: |
          mkdir -p artifacts
          # Only include Python files and dependencies, exclude unnecessary files
          zip -r artifacts/lambda_function.zip . \
            -x "*.git*" "*.github*" "*.DS_Store*" "__pycache__/*" "*.pyc" \
            "artifacts/*" "tests/*" "*.md" "*.txt"
            
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
          
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name hqbot \
            --zip-file fileb://artifacts/lambda_function.zip