name: Deploy to AWS Lambda

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
            uses: actions/checkout@v3

        - name: Zip source code
            run: zip -r lambda_function.zip .

        - name: Deploy to AWS Lambda
            uses: aws-actions/aws-lambda-deploy@v1
            with:
                function-name: hqbot
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ap-southeast-1
                zip-file: lambda_function.zip
